In [6]:
from netCDF4 import Dataset
import pandas as pd
import numpy as np

In [2]:
f = Dataset("A20192132019243.L3m_MO_POC_poc_4km.nc", "r")

In [3]:
for i in f.variables:
    print(i)

poc
lat
lon
palette

In [8]:
print(f.variables.keys())

odict_keys(['poc', 'lat', 'lon', 'palette'])

In [12]:
df_poc = pd.DataFrame()

for i in range(2160,2200):
    for x in range(6480,6500):
        data = {'lat':f.variables['lat'][i],'lon':f.variables['lon'][x],'poc':f.variables['poc'][i][x]}     
        df_poc = df_poc.append(data, ignore_index=True)
        
#df_split = df_conc.loc[(df_conc.lat > 89.6875)&(df_conc.lat < 89.89583)&(df_conc.lon > -20)&(df_conc.lon < 20)]

#print(df_split)
df_poc

              lat        lon      poc
0    -0.020833334  90.020836  38.7998
1    -0.020833334   90.06252  38.7998
2    -0.020833334   90.10418       40
3    -0.020833334  90.145836  40.6001
4    -0.020833334   90.18752  39.6001
5    -0.020833334   90.22918  38.1997
6    -0.020833334  90.270836  38.7998
7    -0.020833334   90.31252       40
8    -0.020833334   90.35418       40
9    -0.020833334  90.395836  40.3999
10   -0.020833334   90.43752  40.1997
11   -0.020833334   90.47918  39.7998
12   -0.020833334  90.520836       38
13   -0.020833334   90.56252  38.1997
14   -0.020833334   90.60418       37
15   -0.020833334  90.645836       37
16   -0.020833334   90.68752       37
17   -0.020833334   90.72918       37
18   -0.020833334  90.770836  38.7998
19   -0.020833334   90.81252  36.7998
20    -0.06250509  90.020836  39.6001
21    -0.06250509   90.06252  39.1997
22    -0.06250509   90.10418  40.3999
23    -0.06250509  90.145836  41.1997
24    -0.06250509   90.18752  40.6001
25    -0.06250509   90.22918  38.7998
26    -0.06250509  90.270836  39.1997
27    -0.06250509   90.31252  39.3999
28    -0.06250509   90.35418  40.1997
29    -0.06250509  90.395836  40.1997
..            ...        ...      ...
770    -1.6041692   90.43752  41.7998
771    -1.6041692   90.47918       41
772    -1.6041692  90.520836  39.3999
773    -1.6041692   90.56252  39.1997
774    -1.6041692   90.60418  41.1997
775    -1.6041692  90.645836  41.1997
776    -1.6041692   90.68752  40.1997
777    -1.6041692   90.72918       40
778    -1.6041692  90.770836  39.6001
779    -1.6041692   90.81252  39.3999
780    -1.6458334  90.020836       35
781    -1.6458334   90.06252  34.1997
782    -1.6458334   90.10418       35
783    -1.6458334  90.145836       35
784    -1.6458334   90.18752  34.1997
785    -1.6458334   90.22918  35.7998
786    -1.6458334  90.270836  35.7998
787    -1.6458334   90.31252       45
788    -1.6458334   90.35418       44
789    -1.6458334  90.395836  45.1997
790    -1.6458334   90.43752  46.3999
791    -1.6458334   90.47918  39.3999
792    -1.6458334  90.520836  37.7998
793    -1.6458334   90.56252       39
794    -1.6458334   90.60418  38.3999
795    -1.6458334  90.645836       40
796    -1.6458334   90.68752       40
797    -1.6458334   90.72918  40.7998
798    -1.6458334  90.770836  40.3999
799    -1.6458334   90.81252       42

[800 rows x 3 columns]

In [21]:
df_poc.poc.describe()

count     800
unique     91
top        --
freq      142
Name: poc, dtype: object